services:
  app:
    image: ${DOCKER_IMAGE:-your-username/yii2-app:latest}
    networks:
      - yii2-network
    volumes:
      - app-data:/var/www/yii2_sample_app
    environment:
      - DB_HOST=db
      - DB_NAME=yii2db
      - DB_USER=yii2user
      - DB_PASSWORD=yii2password
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
    ports:
      - "9000:9000"
    healthcheck:
      test: ["CMD", "php-fpm-healthcheck"]
      interval: 30s
      timeout: 3s
      retries: 3
    depends_on:
      - db

  db:
    image: mysql:8.0
    networks:
      - yii2-network
    environment:
      MYSQL_DATABASE: yii2db
      MYSQL_USER: yii2user
      MYSQL_PASSWORD: yii2password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db-data:/var/lib/mysql
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "3306:3306"

networks:
  yii2-network:
    driver: overlay
    attachable: true

volumes:
  app-data:
  db-data: