---
- name: Setup Docker Swarm Manager
  hosts: manager
  become: yes
  vars:
    docker_image: "slayerop15/yii2-docker-ansible:latest"
    app_dir: "/opt/yii2-app"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - software-properties-common
          - nginx
          - git
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Start and enable Docker
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Add user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Reset SSH connection to apply docker group changes
      meta: reset_connection

    - name: Check if Swarm is initialized
      shell: docker info --format '{{ "{{" }}.Swarm.LocalNodeState{{ "}}" }}'
      register: swarm_status
      changed_when: false

    - name: Initialize Docker Swarm
      shell: docker swarm init --advertise-addr {{ ansible_default_ipv4.address }}
      when: swarm_status.stdout != "active"

    - name: Get worker join token
      shell: docker swarm join-token worker -q
      register: worker_token
      changed_when: false

    - name: Display worker join command
      debug:
        msg: "Workers can join with: docker swarm join --token {{ worker_token.stdout }} {{ ansible_default_ipv4.address }}:2377"

    - name: Create app directory
      file:
        path: "{{ app_dir }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Create docker-stack.yml
      copy:
        src: ../docker-stack.yml
        dest: "{{ app_dir }}/docker-stack.yml"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Configure Nginx
      copy:
        src: ../nginx-conf/yii2-production.conf
        dest: /etc/nginx/conf.d/yii2-app.conf
        backup: yes
      notify: restart nginx

    - name: Remove default nginx site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Test nginx configuration
      command: nginx -t

    - name: Start and enable nginx
      systemd:
        name: nginx
        enabled: yes
        state: restarted

    - name: Pull Docker image
      docker_image:
        name: "{{ docker_image }}"
        source: pull
        force_source: yes
      become_user: "{{ ansible_user }}"

    - name: Deploy application stack
      shell: |
        cd {{ app_dir }}
        docker stack deploy --compose-file docker-stack.yml yii2-app
      become_user: "{{ ansible_user }}"

    - name: Wait for services to be ready
      shell: docker service ls --filter name=yii2-app --format "{{ "{{" }}.Name{{ "}}" }}\t{{ "{{" }}.Replicas{{ "}}" }}"
      register: service_status
      until: service_status.stdout | regex_search('yii2-app_app.*2/2') and service_status.stdout | regex_search('yii2-app_db.*1/1')
      retries: 12
      delay: 10
      become_user: "{{ ansible_user }}"

    - name: Show deployment info
      debug:
        msg: |
          ✅ Manager deployed successfully!
          
          🌐 Application: http://{{ ansible_default_ipv4.address }}
          💚 Health: http://{{ ansible_default_ipv4.address }}/health
          
          📋 Worker join command:
          docker swarm join --token {{ worker_token.stdout }} {{ ansible_default_ipv4.address }}:2377
          
          🔧 Services:
          {{ service_status.stdout }}

  handlers:
    - name: restart nginx
      systemd:
        name: nginx
        state: restarted