---
- name: Setup Docker Swarm Worker with Nginx
  hosts: yii2-workers
  become: yes
  vars:
    nginx_config_source: ../nginx-conf/yii2-production.conf

  tasks:
    - name: Fail if manager_ip or worker_token not provided
      fail:
        msg: "manager_ip and worker_token must be provided as extra vars"
      when: manager_ip is not defined or worker_token is not defined

    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - nginx
          - git
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Start and enable Docker
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Add user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    # Force SSH reconnection for group changes
    - name: Reset SSH connection to apply docker group changes
      meta: reset_connection

    - name: Wait for connection reset
      wait_for_connection:
        delay: 5
        timeout: 30

    # Docker Swarm Join
    - name: Check if already in swarm
      command: docker info --format '{{ "{{" }}.Swarm.LocalNodeState{{ "}}" }}'
      register: swarm_state
      become: no
      changed_when: false

    - name: Join Docker Swarm
      command: docker swarm join --token {{ worker_token }} {{ manager_ip }}:2377
      become: no
      when: swarm_state.stdout != "active"

    - name: Verify swarm membership
      command: docker info --format '{{ "{{" }}.Swarm.LocalNodeState{{ "}}" }}'
      register: swarm_verification
      become: no
      changed_when: false

    # Nginx Configuration for Worker
    - name: Configure Nginx for worker node
      copy:
        src: "{{ nginx_config_source }}"
        dest: /etc/nginx/conf.d/yii2-production.conf
        backup: yes
      notify: restart nginx

    - name: Remove default nginx site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify: restart nginx

    - name: Test nginx configuration
      command: nginx -t
      changed_when: false

    - name: Start and enable nginx
      systemd:
        name: nginx
        enabled: yes
        state: started

    # Pull Docker image to ensure availability
    - name: Pull application image
      command: docker pull slayerop15/yii2-docker-ansible:latest
      become: no
      retries: 3
      delay: 10

    - name: Show worker status
      debug:
        msg: |
          ✅ Worker setup complete!
          
          📍 Node: {{ ansible_hostname }}
          🔗 Swarm Status: {{ swarm_verification.stdout }}
          🎯 Manager: {{ manager_ip }}
          🌐 Access URL: http://{{ ansible_default_ipv4.address }}
          
          ✨ Successfully joined swarm with nginx configured!

  handlers:
    - name: restart nginx
      systemd:
        name: nginx
        state: restarted